### ISSUE TITLE
hub snap is missing hub's man pages

### ISSUE THREAD

**Issue by raphinesse** [felicianotech/hub-snap#25]
As discovered when analyzing github/hub#2353, the `hub` snap is not including any built man pages of `hub`:
```
$ cd /snap/hub/current
$ find | grep man1
./go/src/github.com/github/hub/share/man/man1
./go/src/github.com/github/hub/share/man/man1/hub.1.md
```

I'm running `hub` 2.13.0 on Ubuntu 19.04.

**Comment by jaymzh** [comment]
IT's worth noting here that as of the most recent version `hub help <command>` or `hub --help <command>` or `hub <command> --help` all just run `man hub-<command>` under the hood. And while snapd is still working on how to handle man, the snap should at least include the man pages in the meantime so someone can at least alter their MANPATH and get the help.

**Comment by FelicianoTech** [comment]
I'm investigating.

**Comment by FelicianoTech** [comment]
This has been fixed. Your computer will naturally get the update within 24 hours. If you want to force the install of the fix, you can run the following in a terminal:

```bash
sudo snap refresh hub
```
